sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: 'arnaud.mesureur@gmail.com'
  api_key:
    secure: gykgCqWayJZKbaI20W7Uf835mFLce/m/AAV23XMsUojcbFe0/7cVrJjqH0o9xX/roanslqnKsBlBStMalLz1HMdirHiYWhdlC/jh9ZTZUolSt6O4O8+uRr4q7CfbQG79LeLtEoi1mANxdaH7U8rfrstVMLjv1f/RjIGRobjyqJ+yApc/v1ldTSjTBKawoMOA6EM+0hGNgA/r1NQwAwb3fa7fbMuwmeFgxmWHWBKVjOg1dcbH5EzovC7N/Bs2+Etdq6xioLceR/n1QcpSpAmlp9/8itmO38zFCqBBFgfnczoRqvpf9+AmG5d7wc5JTZ7VxeYZZ+2uX6oqNIJYvUWypX0jfpcLC854Q+QW1mzfi1EG3b+1LdN4UpgGRlK4BqBVOzhDzXTBlRmpyMIn2x9cx8GaxofLDCVoAtSHn8B0fsNggS8MRgJCXYtO4jo6Le/h88m14kYD8y/oIhym+du/QJ0GZ+LPG295Wm2RZF+ScmEn3U+Ko5MP++tyvGTJoKTCDFGCr2UKP21TNyNLdzALWuS6oOoZPBsto5gnIJ1kh60htfBxuXk9Uc5nTtbhiz7rHwjqivj1g/aPdShb3q7ybMskF0T2eA0dE6Nx7+PmEboV7L4e0k0mRflu1E+lrCNtzZ2GgfwPz1M+blIw2CgkKNS3gTfsrCOi5GYOrsW0oAE=
  on:
    tags: true
