sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: arnaud.mesureur@gmail.com
  api_key:
    secure: YDKGFSaoG0G+y3iNiUoCNoD6Db9e1917e15oab9k6XZqsavmBWcE7Oe857FZwT0TqfjJ0trN7ZQD8lFX02MkLSAYyxRaPIEYo4RA83AM/ZxcXh5tsoruEiK4Q8EOugEvYWhVlryq9Ut4MmicDYt3l2dUM67TPtK0nc9DnVlIs+NXRIzmUkhjD7S3K+eTpHqnUI2F3Xb645II7FGf72XvhOZ3n2uN4A0wf4ZCDr2Ni+jj/gaWr5RUgTfxj7ihTeINh6rz8uSzk1gcuO09LA1/Dd69r4PBx2xjI07eq2NasPiShTdbIwZxB7kcM8mOykYVDbiywNkH0BXD2Qid1djuSzkUtIC2kOYfeBWLDBVuzaI7pjaWYkGvugE4dx+ML81wpC88qp8zp8yeia+nFinwSjWmTIfG6+iNhF737NBrRg2bEyVn7AO9azQyPx8lCurSbrkAovsQ3lj4Qr1tqcX3HR36v1GKd1S1DCj1sT2N1EDutkzlmI27W8QMmbD+3rztWeHJIGoKPXlRcozUQUqlAVlrpnTprOVUdwM02CDGgcU/J44HG0iv3WYs29Z3lXwGDqW5cFo0aHQjgVpciNEwJyLozPmW0iBBMQ7XfwuoOQdT04iEhrgwH2Gxag4oFCF7RobCUvWssf/M7moMib4CQY4E79vNXFglnarQLHyVl4A=
  on:
    tags: true
    repo: nsarno/generator-react-zero
