sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: arnaud.mesureur@gmail.com
  api_key:
    secure: uRUH1P6Ab01RM5mt321nclootiE37E0QoI4TWdl8EwUj6vI/Ae/icIJIx8P4UYkMclf+YrRJx0+Sf/ompCwQfR+PcZ9g5T4LrUqbQadVqtBV7oL+cZCW2yM7+fZwZXIPtD0qR/MPnKmmHXQ8aotOK3VUPNefjaW/RZ1LFFIAPhHfFb+Dgtxkf5a6kkli+3ysVhBVwM1kkuKegFdHhCaLjSzzvuQVfat7DTdbjmHVd/KwQgRIzfmi9SJNJ7ESRPmxXhto2cFhj80qllWkKTcdgtsEfuU5BwnVJ8gL3DH4jG5+UnPVPP6C9ZreOdsLKYFC5aiY0vQIOjfuiDNiB7Q6rPjE4k7ZAwXX5UG0ws9LDp0tCDXYLSYVWH3ox4DOMZlJj9v6oUuWwbJvXgSl1ZJ4xc3w8z63I1SjwjBLX3hS/6s9GPisXBh3sNRZod5Q6EtdvR0aXbk9F3XYtDQ4nMa6eSX0zoifzKej+fWe2nGYL7RZMKk6Z1DoriZ5Trrdm2LGiV9XmEzg6tLMxqcgLzGXvemVlK19ajncs/9JMvA8l2AQebPxQSbMQhsUHSAbucupjc1zfJkPlHDpIpQ/Sj44VbDhcuKzEZgyM82nODE3HXk5vjZSGOnmGNnAAzH4Tee2iuSc7gpJ8MWaXHk8KQClJK5Q6mEEkTMiOXb/kRejak8=
  on:
    tags: true
    repo: nsarno/generator-react-zero
